<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <RootNamespace>PortfolioTerminal.Api</RootNamespace>
    <UserSecretsId>portfolio-terminal-app-api-6ee5e467-bd00-4638-82a7-c336f1dc2e69</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
    <PackageReference Include="Microsoft.OpenApi" Version="2.11.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\App.CarService\App.CarService.csproj" />
    <ProjectReference Include="..\App.Data\App.Data.csproj" />
    <ProjectReference Include="..\App.Portfolio\App.Portfolio.csproj" />
  </ItemGroup>
</Project>
